# Generated by Django 3.1.6 on 2021-03-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0002_auto_20210319_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=12)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('propic', models.ImageField(blank=True, default='media/default.jpg', upload_to='profile_pic')),
            ],
        ),
    ]
